CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	brand VARCHAR(255) NOT NULL
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;

CREATE TABLE LOT (
	id INT PRIMARY KEY,
    product_id INT NOT NULL,
    total_amount INT NOT NULL,
    creation_date DATE,
    expiration_date DATE,
    campus_id INT NOT NULL,
FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;